project:
  type: website
  output-dir: docs

execute: 
  echo: false
  warning: false

website:
  title: "CCHA sampling effort"
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: subsampling.qmd
        text: Sub-sampling scheme
      - section: "Results"
        contents:
          - href: richness.qmd
          - href: richnesszone.qmd
          - href: frequencyoccurrence.qmd
          - href: zones.qmd
          - href: elevation.qmd
      - href: conclusions.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

