project:
  type: website
  output-dir: docs
  post-render: mv docs/report/report-draft.docx report/

execute: 
  echo: false
  warning: false

website:
  title: "CCHA sampling effort"
  repo-url: https://github.com/tbep-tech/ccha-sampling-effort
  site-url: https://tbep-tech.github.io/ccha-sampling-effort
  sidebar:
    style: "floating"
    search: true
    tools: 
      - icon: github
        href: https://github.com/tbep-tech/ccha-sampling-effort
    contents:
      - href: index.qmd
        text: Home
      - href: subsampling.qmd
        text: Sub-sampling scheme
      - section: "Results"
        contents:
          - href: richness.qmd
          - href: richnesszone.qmd
          - href: frequencyoccurrence.qmd
          - href: zones.qmd
          - href: elevation.qmd
      - href: conclusions.qmd
    
format:
  html:
    theme: cosmo
    css: styles.css
    code-tools: 
      source: repo

editor: source

filters:
    - lightbox
    
lightbox: auto

