---
title: "Conclusions"
---

* Richness estimates for a site are reduced with lower sample effort
* The amount of reduction in the richness estimated was weakly associated with total species richness at a site
* Richness estimates for a zone are reduced with lower sample effort
* Richness estimates will be systematically lower with reduced effort for zones with overall higher richness.  These include zones...
* Frequency occurrence estimates for individual species will not be systematically different at lower sample effort, but the estimates are imprecise
* Species with higher frequency occurrence will have less precise estimates with reduced effort compared to those with lower frequency occurrence
* Zone identification at each site is not affected by sample effort, although distance estimates decrease slightly.  
* Precision of the distance estimates for each zone decreases with reductions in sample effort, but the decrease is not linear and is affected by the actual zone length and sample interval
* The estimated elevation at which mangrove species are observed will decrease with reductions in sampling effort.  The magnitude and uncertainty of the reduction will increase for species with lower frequency occurrence at a site.
